# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::MovieType`.
# Please instead update this file by running `bin/tapioca dsl Types::MovieType`.

class Types::MovieType
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
