# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `little-plugger` gem.
# Please instead update this file by running `bin/tapioca gem little-plugger`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
