version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
