---
include:
  - "app/**/*.rb"
  - "lib/**/*.rb"
  - "spec/**/*.rb"
exclude:
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - typecheck:typed
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
