---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - require_not_found
  - typecheck:typed
require_paths: []
plugins:
  - solargraph-arc
max_files: 5000
