version: "3.3"
services:
  db:
    image: postgres:9.6.4
    ports:
      - "5432:5432"
  redis:
    image: redis:4.0.8
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
