version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.5.0-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: broad_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - broad-v2-{{ checksum "Gemfile.lock" }}
            - broad-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: broad-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - broad-yarn-{{ checksum "yarn.lock" }}
            - broad-yarn-

      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Npm build
          command: npm run build

      # Store yarn / webpacker cache
      - save_cache:
          key: broad-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - type: shell
        command: |
          cp .env.development .env.test

          # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)


      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - deploy:
          name: Maybe Deploy
          command: |
            ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push dokku@$DEPLOY_HOST:broad master
            fi