# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CheckWaitlistMovieJob`.
# Please instead update this file by running `bin/tapioca dsl CheckWaitlistMovieJob`.

class CheckWaitlistMovieJob
  class << self
    sig { params(movie: T.untyped).returns(T.any(CheckWaitlistMovieJob, FalseClass)) }
    def perform_later(movie); end

    sig { params(movie: T.untyped).returns(T.untyped) }
    def perform_now(movie); end
  end
end
