# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CheckForBetterMovieReleasesJob`.
# Please instead update this file by running `bin/tapioca dsl CheckForBetterMovieReleasesJob`.

class CheckForBetterMovieReleasesJob
  class << self
    sig { returns(T.any(CheckForBetterMovieReleasesJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
