# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeleteOldNewsItemsJob`.
# Please instead update this file by running `bin/tapioca dsl DeleteOldNewsItemsJob`.

class DeleteOldNewsItemsJob
  class << self
    sig { returns(T.any(DeleteOldNewsItemsJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
