# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FetchMovieImagesJob`.
# Please instead update this file by running `bin/tapioca dsl FetchMovieImagesJob`.

class FetchMovieImagesJob
  class << self
    sig { params(movie: T.untyped).returns(T.any(FetchMovieImagesJob, FalseClass)) }
    def perform_later(movie); end

    sig { params(movie: T.untyped).returns(T.untyped) }
    def perform_now(movie); end
  end
end
