# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FetchNewFeedEntriesJob`.
# Please instead update this file by running `bin/tapioca dsl FetchNewFeedEntriesJob`.

class FetchNewFeedEntriesJob
  class << self
    sig { returns(T.any(FetchNewFeedEntriesJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
