# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FetchEpisodeDetailsJob`.
# Please instead update this file by running `bin/tapioca dsl FetchEpisodeDetailsJob`.

class FetchEpisodeDetailsJob
  class << self
    sig { params(episode: T.untyped).returns(T.any(FetchEpisodeDetailsJob, FalseClass)) }
    def perform_later(episode); end

    sig { params(episode: T.untyped).returns(T.untyped) }
    def perform_now(episode); end
  end
end
