# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RateMovieJob`.
# Please instead update this file by running `bin/tapioca dsl RateMovieJob`.

class RateMovieJob
  class << self
    sig { params(movie: T.untyped, rating: T.untyped).returns(T.any(RateMovieJob, FalseClass)) }
    def perform_later(movie, rating); end

    sig { params(movie: T.untyped, rating: T.untyped).returns(T.untyped) }
    def perform_now(movie, rating); end
  end
end
