# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncWatchedEpisodesWithTraktJob`.
# Please instead update this file by running `bin/tapioca dsl SyncWatchedEpisodesWithTraktJob`.

class SyncWatchedEpisodesWithTraktJob
  class << self
    sig { returns(T.any(SyncWatchedEpisodesWithTraktJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
