# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncWatchedMoviesWithTraktJob`.
# Please instead update this file by running `bin/tapioca dsl SyncWatchedMoviesWithTraktJob`.

class SyncWatchedMoviesWithTraktJob
  class << self
    sig { returns(T.any(SyncWatchedMoviesWithTraktJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
