# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncRatedMoviesWithTraktJob`.
# Please instead update this file by running `bin/tapioca dsl SyncRatedMoviesWithTraktJob`.

class SyncRatedMoviesWithTraktJob
  class << self
    sig { returns(T.any(SyncRatedMoviesWithTraktJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
