# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WaitlistTvShowsCheckJob`.
# Please instead update this file by running `bin/tapioca dsl WaitlistTvShowsCheckJob`.

class WaitlistTvShowsCheckJob
  class << self
    sig { returns(T.any(WaitlistTvShowsCheckJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
