# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WaitlistMovieCheckJob`.
# Please instead update this file by running `bin/tapioca dsl WaitlistMovieCheckJob`.

class WaitlistMovieCheckJob
  class << self
    sig { params(movie: T.untyped).returns(T.any(WaitlistMovieCheckJob, FalseClass)) }
    def perform_later(movie); end

    sig { params(movie: T.untyped).returns(T.untyped) }
    def perform_now(movie); end
  end
end
