development:
  adapter: postgresql
  encoding: utf8
  database: broad_development
  username: postgres
  host: db
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 25
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: broad_test
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  host: db
  pool: 5
  port: 5432

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] %>
